// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    DB: D1Database;
}

interface Move {
    name: string
    category: string
    type: string
    pp: number
    power: number
    accuracy: number
    effect: string
    changes?: string
}

interface Pokemon {
    number: number
    name: string
    versions: string
    types: string
    abilities: string
    moves: stirng
    changes?: string
}